export const Colors = {
  SCREEN_BACKGROUND: '#ECF0F4',
  SCREEN_BACKGROUND_DARK: 'rgb(30,32,38)',
  TEXT: '#000000',
  TRIP_CARD_BACKGROUND: '#FFFFFF',
  TRIP_CARD_BACKGROUND_HIGHLIGHTED: '#C6FBF8',
  PRIMARY_TEXT: '#00f1e5',
  SECONDARY_TEXT: '#e8e8e8',
}
